enum forecastDescPT {
  "Sem informação",
  "Céu limpo",
  "Céu pouco nublado",
  "Céu parcialmente nublado",
  "Céu muito nublado ou encoberto",
  "Céu nublado por nuvens altas",
  "Aguaceiros",
  "Aguaceiros fracos",
  "Aguaceiros fortes",
  "Chuva",
  "Chuva fraca ou chuvisco",
  "Chuva forte",
  "Períodos de chuva",
  "Períodos de chuva fraca",
  "Períodos de chuva forte",
  "Chuvisco",
  "Neblina",
  "Nevoeiro ou nuvens baixas",
  "Neve",
  "Trovoada",
  "Aguaceiros e trovoada",
  "Granizo",
  "Geada",
  "Chuva forte e trovoada",
  "Nebulosidade convectiva",
  "Céu com periodos muito nublado",
  "Nevoeiro",
  "Céu nublado"
};

